{% set name = "marshmallow-jsonschema" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marshmallow-jsonschema-{{ version }}.tar.gz
  sha256: f8ce19cfc0edd909e81f141d7420c33544b849bc5ebbfae8f6a3deea5a3b1f47

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - marshmallow >=3.11
    - python >={{ python_min }}

test:
  imports:
    - marshmallow_jsonschema
    - marshmallow_jsonschema.extensions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fuhrysteve/marshmallow-jsonschema
  summary: JSON Schema Draft v7 (http://json-schema.org/) formatting with marshmallow
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fuhrysteve
    - k-dominik
